{{- if not (eq .Values.global.coco.secured  true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rvps-reference-values
  namespace: trustee-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  reference-values.json: |
    [
    ]
{{ end }}