{{ if eq .Values.global.coco.secured  true }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: rvps-policy
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: rvps-policy-cp
      spec:
        remediationAction: enforce
        severity: medium
        object-templates-raw: |
          {{`{{- $pcr8Hash := fromConfigMap "imperative" "initdata" "PCR8_HASH" -}}`}}
          {{`{{- $secretData := (lookup "v1" "Secret" "trustee-operator-system" "pcr-stash").data.json | base64dec | fromJson -}}`}}
          {{`{{- $pcr03 := $secretData.measurements.sha256.pcr03 -}}`}}
          {{`{{- $pcr09 := $secretData.measurements.sha256.pcr09 -}}`}}
          {{`{{- $pcr11 := $secretData.measurements.sha256.pcr11 -}}`}}
          {{`{{- $pcr12 := $secretData.measurements.sha256.pcr12 -}}`}}
          {{`{{- $referenceValues := list (dict "name" "snp_pcr03" "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr03)) (dict "name" "tdx_pcr03" "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr03)) (dict "name" "snp_pcr08" "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr8Hash)) (dict "name" "tdx_pcr08" "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr8Hash)) (dict "name" "snp_pcr09" "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr09)) (dict "name" "tdx_pcr09" "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr09)) (dict "name" "snp_pcr11" "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr11)) (dict "name" "tdx_pcr11" "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr11)) (dict "name" "snp_pcr12" "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr12)) (dict "name" "tdx_pcr12" "expiration" "2027-12-12T00:00:00Z" "value" (list $pcr12)) -}}`}}
          - complianceType: mustonlyhave
            objectDefinition:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: rvps-reference-values
                namespace: trustee-operator-system
              data:
                reference-values.json: '{{`{{ toJson $referenceValues }}`}}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: rvps-placement-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
placementRef:
  name: rvps-placement-rule
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: rvps-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: rvps-placement-rule
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      local-cluster: "true"
---
{{ end }}